version: '3'

networks:
  test_gitlab:
    driver: bridge
    external:
      name: test-gitlab-network

services:
  nginx_1:
    image: nginx:latest
    restart: always
    container_name: nginx_1
    volumes:
      - "/home/test/gitlab/run_official_documentation/containers/nginx/nginx-conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "/home/test/gitlab/run_official_documentation/containers/nginx/nginx-conf/gitlab-http.conf:/etc/nginx/conf.d/gitlab-http.conf:ro"
      - "/home/test/gitlab/run_official_documentation/containers/nginx/nginx-logs:/var/log/nginx"
    ports:
      - '81:80'
    depends_on:
      - gitlab_app_1
    links:
      - gitlab_app_1
    networks:
      test_gitlab:
        aliases:
          - test-gitlab-network

  gitlab_app_1:
    image: 'gitlab/gitlab-ce:latest'
    restart: always
    hostname: 'git'
    container_name: gitlab_app_1
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.example.com'
        # Add any other gitlab.rb configuration here, each on its own line
    expose:
      - "80"
    ports:
      - '80:80'
      - '443:443'
      - '2222:22'
    volumes:
      - '/home/test/gitlab/run_official_documentation/containers/gitlab/gitlab_config:/etc/gitlab'
      - '/home/test/gitlab/run_official_documentation/containers/gitlab/gitlab_logs/logs:/var/log/gitlab'
      - '/home/test/gitlab/run_official_documentation/containers/gitlab/gitlab_data/data:/var/opt/gitlab'
    depends_on:
      - postgresql_1
      - redis_1
    links:
      - postgresql_1
      - redis_1
    networks:
      test_gitlab:
        aliases:
          - test-gitlab-network

  postgresql_1:
    image: postgres:latest
    restart: always
    container_name: postgresql_1
    environment:
      - POSTGRES_PASSWORD=Your_db-password
    ports:
      - '5433:5432'
    volumes:
      - '/home/test/gitlab/run_official_documentation/containers/postgresql/postgresql-data:/var/lib/postgresql/data'
    networks:
      test_gitlab:
        aliases:
          - test-gitlab-network

  redis_1:
    restart: always
    image: redis:latest
    container_name: redis_1
    ports:
      - "6379:6379"
    volumes:
     - "/home/test/gitlab/run_official_documentation/containers/redis/redis-data:/data"
    networks:
      test_gitlab:
        aliases:
          - test-gitlab-networkt
